-- AlterTable
ALTER TABLE `Job` ADD COLUMN `presetParams` JSON NULL;
ALTER TABLE `Job` MODIFY `type` ENUM('PROBE', 'IMAGE_VARIANTS', 'VIDEO_TRANSCODE', 'AUDIO_EXTRACT', 'EDIT') NOT NULL;
ALTER TABLE `Derivative` MODIFY `kind` ENUM('THUMBNAIL', 'PREVIEW', 'POSTER', 'VIDEO_720P', 'AUDIO_MP3', 'EXPORT') NOT NULL;
